ErpContent/Controllers/ChiefEditorController.cs
using EditorsCommon;
using EditorsCommon.Publication;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Profile;
using System.Web.Script.Serialization;
using System.Web.Security;

namespace ErpContent.Controllers
{

    public class ChiefEditorController : System.Web.Mvc.Controller
    {

        private IIssueStorage _issueStorage;


        public ChiefEditorController(IIssueStorage issueStorage)
        {
            _issueStorage = issueStorage;
        }


        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameChiefEditor + "," + EditorsCommon.Constants.roleNameAdmin)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult Index()
        {
            
            return View("ChiefDashboard");
        }


        
        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameChiefEditor + "," + EditorsCommon.Constants.roleNameAdmin)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult TastingEvents(int id)
        {
            return Json(_issueStorage.GetAssignments(id), JsonRequestBehavior.AllowGet);
        }




        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult Publications()
        {
            return Json(_issueStorage.GetPublications(), JsonRequestBehavior.AllowGet);
        }



        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 300, VaryByParam = "none")]
        public ActionResult GetSubEditors()
        {
           string[] un =  Roles.GetUsersInRole(EditorsCommon.Constants.roleNameEditor);

           HashSet<string> unique = new HashSet<string>();
           foreach (var n in un)
           {
               unique.Add(n);
           }

           un = Roles.GetUsersInRole(EditorsCommon.Constants.roleNameSubEditor);
           foreach (var n in un)
           {
               if (!unique.Contains(n))
               {
                   unique.Add(n);
               }
           }



           List<Object> reviewers = new List<Object>();
           foreach (var n in unique)
           {
               MembershipUser mu = ((ERP.Providers.SqlMembershipProvider)Membership.Provider).GetUser(n, false);
               ProfileBase p = ProfileBase.Create(mu.UserName);

               if (mu != null)
               {
                   reviewers.Add(new { id = (int)mu.ProviderUserKey,  name = p["FirstName"] + " " + p["LastName"] });
               }
           }


           return Json(reviewers, JsonRequestBehavior.AllowGet);
        }




        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 300, VaryByParam = "none")]
        public ActionResult GetEditors()
        {
            string[] un = Roles.GetUsersInRole(EditorsCommon.Constants.roleNameEditor);

            HashSet<string> unique = new HashSet<string>();
            foreach (var n in un)
            {
                unique.Add(n);
            }



            List<Object> reviewers = new List<Object>();
            foreach (var n in unique)
            {
                MembershipUser mu = ((ERP.Providers.SqlMembershipProvider)Membership.Provider).GetUser(n, false);
                ProfileBase p = ProfileBase.Create(mu.UserName);

                if (mu != null)
                {
                    reviewers.Add(new { id = (int)mu.ProviderUserKey, name = p["FirstName"] + " " + p["LastName"] });
                }
            }


            return Json(reviewers, JsonRequestBehavior.AllowGet);
        }



        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 300, VaryByParam = "none")]
        public ActionResult GetReviewers()
        {
            string[] un = Roles.GetUsersInRole(EditorsCommon.Constants.roleNameReviewer);

            List<Object> reviewers = new List<Object>();
            foreach (var n in un)
            {
                MembershipUser mu = ((ERP.Providers.SqlMembershipProvider)Membership.Provider).GetUser(n, false);

                ProfileBase p = ProfileBase.Create(mu.UserName);

                if (mu != null)
                {
                    reviewers.Add(new { id = (int)mu.ProviderUserKey,  name = p["FirstName"] + " " + p["LastName"] });
                }
            }


            return Json(reviewers, JsonRequestBehavior.AllowGet);
        }



    }
}

ErpContent/Controllers/EditorAreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ErpContent.Controllers
{
    public class EditorAreaController : Controller
    {
        //
        // GET: /EditorArea/


        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameEditor 
            + "," + EditorsCommon.Constants.roleNameSubEditor 
            + "," + EditorsCommon.Constants.roleNameAdmin)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult Index()
        {
            return View("EditorDashboard");
        }

    }
}

ErpContent/Controllers/ProofreaderAreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ErpContent.Controllers
{
    public class ProofreaderAreaController : Controller
    {
        //
        // GET: /EditorArea/


        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameEditor 
            + "," + EditorsCommon.Constants.roleNameSubEditor 
            + "," + EditorsCommon.Constants.roleNameAdmin)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult Index()
        {
            return View("ProofreaderDashboard");
        }

    }
}

ErpContent/Controllers/TastingNoteController.cs
using EditorsCommon;
using EditorsCommon.Publication;
using Excel;
using log4net;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using System.Data;
using System.Web.Profile; 

namespace ErpContent.Controllers
{
    public class TastingNoteController : Controller
    {

        private static ILog log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);


        private ITastingNoteStorage _storage;

        /// <summary>
        /// IOC container should provide implementation of IAssignmentStorage
        /// </summary>
        /// <param name="assignmentStorage"></param>
        public TastingNoteController(ITastingNoteStorage storage)
        {
            _storage = storage;
        }
        
        //
        // GET: /Assignment/
        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        public ActionResult Index()
        {
            return View();
        }


        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult GetNotesByTastingEvent(int eventId)
        {

            var result = _storage.SearchTastingNoteByTastingEvent(eventId);

            //result = from r in result orderby r.producer select r;
            //
            // implicitly use IComparable<TastingNote>, so, notes would be sorted how it is defined
            // in  public int CompareTo(TastingNote other) method of the TastingNote
            //
            result = from r in result orderby r select r;


            return Json(result, JsonRequestBehavior.AllowGet);

        }


        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult GetNotesByVinN(int vinN)
        {

            var result = _storage.SearchTastingNoteByVinN(vinN);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult GetNotesByWineN(int wineN)
        {

            var result = _storage.SearchTastingNoteByWineN(wineN);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult GetNotesByProducerN(int producerN)
        {

            var result = _storage.SearchTastingNoteByProducerN(producerN);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [HttpPost]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        public ActionResult GetNewNoteForEvent(int eventId, string vin = null,string vintage = null)
        {

            var result = new TastingNote() { tastingEventId = eventId, tastingDate = DateTime.Now };

            if (vin != null)
            {
                var v = new JavaScriptSerializer().Deserialize<VinN>(vin);

                result.producer = v.producer;
                result.wineName = v.label;

                result.country = v.country;
                result.region = v.region;
                result.location = v.location;
                result.locale = v.locale;
                result.site = v.site;

                result.variety = v.variety;
                result.color = v.colorClass;
                result.dryness = v.dryness;

                result.wineType = v.wineType;
            }
            else
            {
                result.producer = "";
                result.wineName = "";

                result.country = "";
                result.region = "";
                result.location = "";
                result.locale = "";
                result.site = "";

                result.variety = "";
                result.color = "";
                result.dryness = "";

                result.wineType = "";
            }

            if (vintage != null)
            {
                result.vintage = vintage;
            }
            else
            {
                result.vintage = "";
            }



            return Json(result, JsonRequestBehavior.AllowGet);
        }





        /// <summary>
        /// 
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        [HttpPost]
        public ActionResult SetTastingNoteState(int noteId, int stateId)
        {

            var result = _storage.SetNoteState(noteId, stateId);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        private static int tmpNoteId = 0;
        private static string cartSessionName = "tastingNodeCart";

        /// <summary>
        /// 
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        [HttpPost]
        public ActionResult AddTastingNoteToCart(String str)
        {
            var tn = new JavaScriptSerializer().Deserialize<TastingNote>(str);
            tn.id = tmpNoteId++;

            List<TastingNote> cart = Session[cartSessionName] as List<TastingNote>;

            if (cart == null)
            {
                cart = new List<TastingNote>();
                Session[cartSessionName] = cart;
            }

            cart.Add(tn);

            return Json(tn, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        [HttpPost]
        public ActionResult GetTastingNoteCart()
        {
            List<TastingNote> cart = Session[cartSessionName] as List<TastingNote>;

            if (cart == null)
            {
                cart = new List<TastingNote>();
                Session[cartSessionName] = cart;
            }

            return Json(cart, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        [HttpPost]
        public ActionResult DeleteTastingNoteFromCart(String str)
        {
            var tn = new JavaScriptSerializer().Deserialize<TastingNote>(str);

            List<TastingNote> cart = Session[cartSessionName] as List<TastingNote>;
            if (cart == null || cart.RemoveAll(t => t.id == tn.id) != 1)
            {
                tn = null;
            }

            return Json(tn, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        [HttpPost]
        public ActionResult DeleteAllTastingNotesFromCart()
        {
            List<TastingNote> cart = Session[cartSessionName] as List<TastingNote>;
            if (cart != null)
            {
                cart.Clear();
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }



        /// <summary>
        /// 
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        [System.Web.Mvc.Authorize(Roles = EditorsCommon.Constants.roleNameAll)]
        [OutputCache(Duration = 0, VaryByParam = "none")]
        [HttpPost]
        public ActionResult AddTastingNote(String str)
        {
            return Json(this.CreateNewTastingNoteRecord(str), JsonRequestBehavior.AllowGet);
        }

        /**
         * Create a new  tasting note record
         * 
         * @param       String      stringOject         String representation of a note
         * @param       Boolean     isImport            This is a boolean value to toggle if this call is being called by the import process, or not. 
         */
        private TastingNote CreateNewTastingNoteRecord(string stringObject, Boolean isImport = false) {

            var objectToEvaluate = new JavaScriptSerializer().Deserialize<TastingNote>(stringObject);


            if (!isImport)
            {
                var maturityId = objectToEvaluate.maturityId;
                int maturityIdValue = 5;

                switch (maturityId.ToString())
                {
                    case "Young":
                        maturityIdValue = 0;
                        break;
                    case "Early":
                        maturityIdValue = 1;
                        break;
                    case "Mature":
                        maturityIdValue = 2;
                        break;
                    case "Late":
                        maturityIdValue = 3;
                        break;
                    case "Old":
                        maturityIdValue = 4;
                        break;
                }

                objectToEvaluate.maturityId = maturityIdValue;
            }



            objectToEvaluate.userId = (int)Membership.GetUser(User.Identity.Name).ProviderUserKey;

ErpContent/Views/Shared/_ArticleEntityJScripts.cshtml
<script type="text/javascript">

    // Represents an article entity
    function ArticleEditModel() {
        self.ID = 0;
        self.PublicationID = 0;
        self.Publication = '';
        self.AuthorId = 0;
        self.AuthorName = '';
        self.Author = '';
        self.Title = '';
        self.ShortTitle = '';
        // self.Datetime = ''; 
        self.Notes = '';
        self.MetaTags = '';
        self.Event = '';
        self.CuisineID = 0;
        self.Cuisine = '';
        self.LocCountryID = 0;
        self.LocRegionID = 0;
        self.locLocationID = 0;
        self.WF_StatusID = 0;
        self.OldArticleIdN = 0;
        self.OldArticleId = 0;
        self.OldArticleIdNKey = '';
    }

    //
    // Joshua see my comments below
    function ArticleModel(source) {

        var self = this;
        //
        // this is a helper function, acutally wrapper around erp.utils.Json2Date(options.data)
        // jus to make call of that function shorter
        //
        var dt2js = function (options) { return erp.utils.Json2Date(options.data) };

        //
        // this is a helper function and we have to use it before calling ajax or when we need object without observables
        //
        //
        self.toObject = function () {
            return ko.mapping.toJS(self);
        }

        //
        // helper function. it transform plain java script object into object where members will be trasform into
        // observables. see http://knockoutjs.com/documentation/plugins-mapping.html for details
        //
        // in the following example, all members from supplied object will be transformed into obeservable.
        // if supplied object has "Date","Created","Updated" member they will be converted from .net json date into javascript date
        //
        //  Let assume that you are getting Article object in JSON format from server. Declaration of the class is like
        //
        // public class Article
        // {
        //  public int? ID { get; set; }
        //  public int? PublicationID { get; set; }
        //  public string Publication { get; set; }
        //  public int? AuthorId { get; set; }
        //  public string Author { get; set; }
        //  public string Title { get; set; }
        //  public string ShortTitle { get; set; }
        //  ....
        //
        //  if we call
        //   var v = ko.mapping.fromJS(o);
        //
        //   it creates for us object where all members will be presented as observables
        //
        //
        //
        //

        self.fromObject = function (o) {

            ko.mapping.fromJS(o  // source
                , {
                    // "Date": { create: dt2js }
                    "Created": { create: dt2js }
                    , "Updated": { create: dt2js }
                }
                , self    // target
                );
        }


        //
        // here we call our transformation plain java script object to object with observables
        //
        self.fromObject(source);

        self.editArticle = function () {

            self.init = function () {

                self.validator = $("#article-form").validate({ debug: true });
            };

            self.validate = function () {
                var validationResult = true;
                validationResult = self.validator.form();
                if (!validationResult)
                    self.validator.showErrors();
                return validationResult;
            }

            self.save = function (self) {

                var objectToSave = self.toObject();

                objectToSave.Notes = escape(CKEDITOR.instances.Notes.getData());

                $.ajax({
                    type: 'POST',
                    url: '@Url.Content("~/Article/UpdateArticle")',
                    data: { article: JSON.stringify(objectToSave) },
                    success: function (result) {

                        var notesContainer = unescape(result.Notes);
                        result.Notes = notesContainer;

                        var articleModelObject = ArticleModel(result);

                        pageData.drillDown("article-preview-template", articleModelObject);

                    },
                    error: function (request, status, error) {

                        PAGE_CONTEXT.error(request, status, error)
                    }
                });
            }

            var dialogBox = pageData.OpenDialog(self, self, "article-form-template");

            dialogBox.dialog("option", "title", "Edit Article");
            dialogBox.dialog("option", "width", 850);
            dialogBox.dialog("option", "height", 700);

            CKEDITOR.replace("Notes");
        }

        self.loaded = false;
    }

</script>

ErpContent/Views/Shared/_ArticleFormTemplate.cshtml
<script id="article-form-template" type="text/html">

    <br />
    <form name="article-form" id="article-form" action="#">
        <div class="row form-group">
            <div class="col-sm-3">Title: </div>
            <div class="col-sm-8"><input class="form-control input-sm" id="Title" name="Title" data-bind="value: Title, valueUpdate: 'blur'" required /></div>
        </div>

        <div class="row form-group">
            <div class="col-sm-3">Short Title: </div>
            <div class="col-sm-8"><input class="form-control input-sm" id="ShortTitle" data-bind="value: ShortTitle, valueUpdate: 'blur'" required /></div>
        </div>

        <div class="row form-group">
            <div class="col-sm-3">Author: </div>
            <div class="col-sm-8"><input class="form-control input-sm" id="Author" data-bind="value: Author, valueUpdate: 'blur'" required /></div>
        </div>

        <div class="row form-group">
            <div class="col-sm-3">Notes: </div>
            <div class="col-sm-8"><textarea class="btn-toolbar form-control input-sm" data-rol="editor-toolbar" data-target="#Notes" runat="server" name="Notes" id="Notes" rows="20" data-bind="value: Notes, valueUpdate: 'blur'" required></textarea></div>
        </div>

    </form>
</script>

ErpContent/Views/Shared/_ArticlePreviewTemplate.cshtml
<script id="article-preview-template" type="text/html">

    <div class="row">
        <div class="col-sm-7">
            <h2 data-bind="text: Title"></h2>
            <h4 data-bind="text: ShortTitle"></h4>
            <div>
                by: <span data-bind="text: Author"></span>
            </div>
        </div>

        <div class="col-sm-3 pull-right">
            <a href="#" class="btn btn-xs pull-right" data-bind="click: $root.drillUp , clickBubble: false"><span class='glyphicon glyphicon-arrow-left' title="Back to Publication List"></span>&nbsp;Go Back to Assignment</a><br />
            <a href="#" data-bind="click: editArticle" class="btn btn-xs pull-right" style="margin-left: 30px;"><span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit aticle</a>
        </div>
    </div>

    <div class="row">
        <div data-bind="html: Notes;" id="notes-display"></div>
    </div>


</script>

ErpContent/Views/Shared/_DisableBrowserBackButton.cshtml
<script type="text/javascript">
    function noBack() {
        window.history.forward();
    }

    $(document).ready(function () {
        noBack();
    });
</script>

ErpContent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/erp")
        @RenderSection("scripts", required: false)
    </body>
</html>

ErpContent/Views/Shared/_LayoutBootstrap.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - ERP Editors Portal</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />

    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" media="screen">
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" media="screen"/>
    <link href='@Url.Content("~/Content/erp.css")' rel="stylesheet" media="screen"/>

<style>


  .alter-backgound:nth-child(2n+1) {
       background-color: #dff0d8;
    }


     #spinnerImage {
          display: none;
     }

     .popup-content-box{
      background-color: white;
      position: fixed;
      margin: 0px auto;
      top: 50%;
      left: 50%;
      z-index: 11;
      -webkit-transform: translate(-50%, -50%);
      -moz-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
      -o-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);
}
</style>


</head>






<body>

    @{
        if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
            {
               @Html.AntiForgeryToken();
            }
        }
    }

    <header>


        <div id="SpinnerContainer" class="popup-content-box">
             <img src="~/Images/spinner.gif" id="spinnerImage" title="working..." />
        </div>


        <div class="navbar navbar-inverse navbar-fixed-top " role="navigation">
            <div class="col-lg-3">
                 <h5><span id="pgTtl">@ViewBag.PageTitle</span></h5>  
            </div>
            <div class="col-lg-4">
                 <h3><span ></span></h3>  
            </div>
            <div class="col-lg-5">

                <nav class="navLinks" role="navigation">
                    <ul class="nav navbar-nav navbar-right">
                       

                         @if (Roles.IsUserInRole(EditorsCommon.Constants.roleNameChiefEditor) ||  Roles.IsUserInRole(EditorsCommon.Constants.roleNameAdmin))
                            {
                              <li class="">@Html.ActionLink("Editor-in-Chief", "Index", "ChiefEditor")</li>                        
                            }

                         @if (Roles.IsUserInRole(EditorsCommon.Constants.roleNameReviewer) )
                            {
                              <li class="">@Html.ActionLink("Reviewer", "Index", "Reviewer")</li>
                            }
                         @if (Roles.IsUserInRole(EditorsCommon.Constants.roleNameEditor) )
                            {
                              <li class="">@Html.ActionLink("Editor", "Index", "EditorArea")</li>
                            }
                         @if ( Roles.IsUserInRole(EditorsCommon.Constants.roleNameSubEditor))
                            {
                              <li class="">@Html.ActionLink("Proofreader", "Index", "ProofreaderArea")</li>
                            }

                         @if ( Roles.IsUserInRole(EditorsCommon.Constants.roleNameAdmin))
                            {
                              <li class="">@Html.ActionLink("Admin", "Index", "Admin")</li>
                            }

                        <li class="">
                            @if (Request.IsAuthenticated)
                            {
                                <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                            }
                            else
                            {
                                @Html.ActionLink("Log In", "Login", "Account")
                            }
                        </li>
                    </ul>
                </nav>

            </div>
        </div>
    </header>

    <div class="container-fluid" id="main">
        <div class="row-fluid">
            <!--left nav-->
            @if(IsSectionDefined("LeftMenu")){
                @RenderSection("LeftMenu", required: false)
            }else{
              <div class="col-sm-2">
                        <div class="list-group">
                            <a class="list-group-item active" href="/chiefeditor/Index">Publications</a>
                            <a class="list-group-item" href="/Home/ShowTemporaryPage">Reviewers</a>
                            <a class="list-group-item" href="/Home/ShowTemporaryPage">Producer Profile</a>
                            <a class="list-group-item" href="/Home/ShowTemporaryPage">Vintage Profile</a>
                            <!-- <a class="list-group-item" href="/Admin/Producers">Producers</a> -->
                            <a class="list-group-item" href="/Home/ShowTemporaryPage">Wines</a>
                            <a class="list-group-item" href="/Home/ShowTemporaryPage">Search Articles</a>
                            <!-- <a class="list-group-item" href="/Admin/Wines">Wine Type</a> -->
                            <!-- <a class="list-group-item" href="/Admin/Wines">Wine Variety</a> --> 
                        </div>
                </div>
            }


            <!-- main content-->
            <div class="col-sm-10">
                <div id="body" class="container-fluid">
                    @RenderSection("featured", required: false)
                    <section class="content-wrapper main-content clear-fix">
                    @RenderBody()
                    </section>
                </div>
            </div>
        </div>
    </div>

    <footer>
        <div id="footer_content">
            <div style="max-width: 600px; margin: 0 auto; text-align: center">
                eRobertParker.com<sup>SM</sup> is a service of The Wine Advocate, Inc, 
                        Email: <a href="mailto:info@erobertparker.com">info@erobertparker.com</a><br />
                Copyright © 2001-2013  - The Wine Advocate, Inc.
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/erp")


<script type="text/javascript">
    //
    // this is global setting. could be used in js file while calling ajax get/post
    //
    erp.wsf_path = '@Url.Content("~/")';
</script>

    @RenderSection("scripts", required: false)


</body>
</html>